### ISSUE TITLE
press and hold

### ISSUE THREAD

**Issue by eadf** [thomasfredericks/Bounce2#13]
I needed two functions in one button so added a [`duration()` method ](https://github.com/eadf/Bounce2) to your class.
It simply returns the period [ms] the pin has been in current state (totally undisturbed - flatline)

If you think this is something you would like in your library i can make a pull request.
Or you can add it yourself, it's effectively a one-liner.

**Comment by thomasfredericks** [comment]
I will look into it, but if I recall correctly, there was an issue with the BOUNCE_LOCK-OUT mode.

**Comment by eadf** [comment]
An alternative would be to keep another timer value that remembers when the output value of the debouncer changed. 

Perhaps that's more semantically correct, a user of the debouncer that wants to know if the button has been pressed for 1 seconds or more doesn't care if there were some jitter 10ms ago.

**Comment by MrHaroldA** [comment]
Isn't this as simple as to expose `previous_millis` as public? In my code I have to declare and fill my own variable to store exactly the same data to check if a switch is pressed long.

Anyway: this would be a very welcome addition for me.

**Comment by thomasfredericks** [comment]
> Isn't this as simple as to expose previous_millis as public? In my code I have to declare and fill my own variable to store exactly the same data to check if a switch is pressed long.

No. As @eadf notes, previous_millis is an internal timer that does not necessarily match the duration of a press. 

If someone wants to code and test it, I will try to integrate it.

**Comment by thomasfredericks** [comment]
Okay, in the new "duration" branch (https://github.com/thomasfredericks/Bounce2/tree/Duration) I added two methods:
* `duration()` that returns how long the current state has been lasting
* `previousDuration()` that returns how long the previous state has been lasting

What do you think?

**Comment by DrFirexx** [comment]
Hi where is this previousDuration() I can't see it in the code

**Comment by MrHaroldA** [comment]
Can't find it either; but thank you for the reminder to check this out ;)

**Comment by DrFirexx** [comment]
Yeah I'm trying to implement a pressed button using duration() but can't get hold of it as it returns 0 whenever button move do you have any tip? I'm quite new to all of this.

**Comment by thomasfredericks** [comment]
This was implemented in a branch. It was removed when the branch was merged for release as it was not sufficiently tested. I added a test ```previousMillis()``` in the master branch,

**Comment by thomasfredericks** [comment]
Yes, in the examples. https://github.com/thomasfredericks/Bounce2/tree/master/examples/more/duration

**Comment by pReya** [comment]
> Yes, in the examples. https://github.com/thomasfredericks/Bounce2/tree/master/examples/more/duration

Somehow, the example called `duration.ino` actually doesn't use the `duration()` function. Is this on purpose?

**Comment by thomasfredericks** [comment]
Oups. Sorry. You are right. The example needs to be updated. I will do it once I get back from vacation.

**Comment by pReya** [comment]
@thomasfredericks Not trying to annoy you on vaction ;) But I'd really appreciate a better example.

**Comment by thomasfredericks** [comment]
No worries @pReya , I uploaded 3 new duration examples in the "examples/more" folder: https://github.com/thomasfredericks/Bounce2/tree/master/examples/more/

**Comment by thomasfredericks** [comment]
Please note I changed duration() to currentDuration() to avoid any confusion.
currentDuration() = duration of current state
previousDuration() = duration of previous state

**Comment by pReya** [comment]
Thank you so much! Appreciate it a lot. I think it would be a good idea to add the term "long press" or "button hold" to the folders/filenames/readme, because it's a term that's googled a lot. Might bring new users to the library (if that's what you're after).
