### ISSUE TITLE
Repeating issue.

### ISSUE THREAD

**Issue by gregwinn** [thomasfredericks/Bounce2#18]
Hello,
     I am having an issue with the following code:

Converting an old keyboard from a TI-99 to USB.

```
#include <Bounce2.h>
const int bounceDelay = 90;

Bounce wire1  = Bounce();

void setup(){
  pinMode(0, INPUT);  // 1
  wire1.attach(0);
  wire1.interval(bounceDelay);
}

void loop(){
  wire1.update();
  if(wire1.read()){
    Serial.println("Y");
  }
}
```

When I launch the serial monitor and press the button (pressing it just once) I get about 50 or so 'Y's... I am expecting to press a button and get just one 'Y'. 

What am I doing wrong, and how would I correct this? Any help would be great, thanks!!

**Comment by thomasfredericks** [comment]
Please check the «change» example. 
read() returns the state of the state of the pin. If you want to trigger an event the moment the state changes, use fell() or rose().
