### ISSUE TITLE
Could you ask for inclusion of this library in Arduino's Board Manager? 

### ISSUE THREAD

**Issue by q2dg** [thomasfredericks/Bounce2#19]
This would give more visibility to this library, I think.
Thanks

**Comment by thomasfredericks** [comment]
I guess you mean Arduino's Library Manager.
Sure, I will read about it.

**Comment by rhettc** [comment]
looks closed to me

**Comment by PaulStoffregen** [comment]
Looks like the only thing you need to do is open an issue on Arduino's tracker, asking them to add your library.

They do have some requirements (library.properties, tags, releases), but you've already done that work.

**Comment by thomasfredericks** [comment]
Will do.

**Comment by rhettc** [comment]
To clarify, this library is already included in the Arduino Library Manager. However, it's using the 2.1 tag, and we'd probably benefit from a new release.

**Comment by thomasfredericks** [comment]
Ok, I made a new release. It should eventually update automatically I think.

**Comment by rhettc** [comment]
Confirmed that the Library Manager has picked up on version 2.2.0 
Awesome
