### ISSUE TITLE
State change triggered only the first time

### ISSUE THREAD

**Issue by gfoiani** [thomasfredericks/Bounce2#30]
Hi all,

I'm using ESP8266 and trying both change and retrigger examples with a button and a led.
State change (rose and fell) is triggered only the first time I push the button and then it becomes unresponsive.
Any idea about the reason?

Thanks

**Comment by thomasfredericks** [comment]
Do you have pull-ups or pull-downs?

**Comment by gfoiani** [comment]
Sorry, I was missing pull down resistor.
