### ISSUE TITLE
Best method for an array of buttons?

### ISSUE THREAD

**Issue by IainIsCreative** [thomasfredericks/Bounce2#31]
Hey there!

I've recently been using `Bounce2` in one of my Arduino projects, and it works well! I have a query though — what's the best method for it to work on an array of buttons? I'm trying to work with a few buttons and store them as an array to work in a `for` loop.

I have seen the two button example, but what is the best method to work with an array of buttons, instead of hard coding every button and debouncer variable?

Many thanks in advance!

**Comment by thomasfredericks** [comment]
Just create an array of Button objects, then set the `.attach( # ) `and ` .interval( ms )` of each.

Example from Arduino.cc : http://forum.arduino.cc/index.php?topic=42943.msg311200#msg311200
