### ISSUE TITLE
Reverse Read logic for switches wired with pullups

### ISSUE THREAD

**Issue by moderndevice** [thomasfredericks/Bounce2#34]
It would be handy if the Bounce library had an overloaded constructor

Bounce button1 = Bounce(buttonPin1, 10, PULLUP );
so that  if (button1.read()) would return true when the button was pressed

maybe it would add too much complexity though to reverse all the rising and falling functions.

**Comment by thomasfredericks** [comment]
Hi. Thank you for your suggestion, but I prefer not to change any public methods of the library.
