### ISSUE TITLE
Support direct cloning into library folder

### ISSUE THREAD

**Issue by felicitus** [thomasfredericks/Bounce2#4]
When I clone this library from ~/Arduino/libraries, I end up with an extra directory:

Bounce-Arduino-Wiring/Bounce2

It would be better if the repository name would be changed to Bounce2 and no subdirectory within the repository for easier cloning.

**Comment by thomasfredericks** [comment]
Hum, the problem is that the folder will appear as Bounce-Arduino-Wiring in the Arduino IDE.

**Comment by thomasfredericks** [comment]
Ok, done. Is this ok?

**Comment by nysander** [comment]
great thank you
