### ISSUE TITLE
pinMode and digitalRead

### ISSUE THREAD

**Issue by capedra** [thomasfredericks/Bounce2#43]
Hello, after the last upgrade from the library I've been facing the following errors on PlatformIO's compilation:
```
Bounce2.h:90:61: error: 'digitalRead' was not declared in this scope
Bounce2.h:95:26: error: 'pinMode' was not declared in this scope
```
both errors can be solved putting the following line on the first line of Bounce2.h file:
```
#include <Arduino.h>
```

**Comment by thomasfredericks** [comment]
Ah, ok, yes thank you. Fixed.
