### ISSUE TITLE
Multiple intervals

### ISSUE THREAD

**Issue by milesfrankland** [thomasfredericks/Bounce2#46]
Hi,
Enhancement suggestion:
When you select the interval - possibly have another function that requires 2x variables.  The off bounce and the on bounce.
This will allow you to say that it has to be on for 100ms before changeover and off for 1000ms before changeover (for example).
What do you think?

**Comment by thomasfredericks** [comment]
Well you can set the interval when the state changes with `interval` without adding any overhead. While Bounce2 will work with long delay times its design is targeted for debouching inputs rather than measuring long presses.
