### ISSUE TITLE
Feature request: .changed()

### ISSUE THREAD

**Issue by septillion-git** [thomasfredericks/Bounce2#54]
No idea why I didn't implement this is the past when I made changes to Bounce2 but why only let .update() return if it changed. There are situations you don't care if it's a .fell() or a .rose() but now you have to change both (which is even extra work because it's made out the current state and the fact if it changed) to simply see if the pin changed.

**Comment by thomasfredericks** [comment]
I am sorry, I don't understand.

**Comment by septillion-git** [comment]
Sorry, should have explained it a bit more. But in short 👼 :
```C++
bool Bounce::changed()
{
    return getStateFlag(CHANGED_STATE);
}
```

**Comment by thomasfredericks** [comment]
Ok, I added a protected `changed()` function in the testing branch: https://github.com/thomasfredericks/Bounce2/tree/Testing

Tell me if it is what you want and if it works.

**Comment by septillion-git** [comment]
I don't know why you want it protected? Just have it public 😃

**Comment by thomasfredericks** [comment]
Oups

**Comment by MartinNel** [comment]
The changed `function() `in the header uses a literal `CHANGED_STATE`, which is not defined in the header file. This gives a compilation error. I suggest moving the literal(s) from the H to the CPP file.

**Comment by thomasfredericks** [comment]
Thank you @MartinNel
Fixed
