### ISSUE TITLE
Add separate up/down timeouts

### ISSUE THREAD

**Issue by skorokithakis** [thomasfredericks/Bounce2#65]
My use case is one where I have a light sensor that goes low when something blocks a (closing) door. When it goes low, it does so fairly immediately with little noise, but high is more noisy (because it's floating and the pullup resistor is a bit weird).

It would be very useful if I could define a different interval for going low vs going high. I care about seeing a low immediately (I don't want the door to hit whatever is in the way) and don't mind false positives, plus low is not as noisy so a smaller interval is more reliable. The high interval could be 300 ms, since I don't really care to be quick about detecting when the obstacle has left.

**Comment by thomasfredericks** [comment]
When the state changes just change the interval. Also, it seems your problem is more hardware than software.
