### ISSUE TITLE
Debouncer::getStateFlag() and Debouncer::read() should be const

### ISSUE THREAD

**Issue by DanForever** [thomasfredericks/Bounce2#76]
It's causing a warning for me in the compiler:

`warning: passing 'const Bounce2::Button' as 'this' argument discards qualifiers [-fpermissive]`

I suspect the only reason this isn't a bigger issue is the default use of "-fpermissive"

**Comment by thomasfredericks** [comment]
Hum, I do not understand. Could you elaborate?

**Comment by DanForever** [comment]
The library needs a bit of const-correctness love. If you need I can create a pull request showing what I mean

**Comment by thomasfredericks** [comment]
Sure.

**Comment by DanForever** [comment]
Pull request made: #78

**Comment by thomasfredericks** [comment]
Was merged. Thank you.

**Comment by DanForever** [comment]
Glad I could help :)
